defaults:
  actions:
    queue:
      name: default
      method: squash

queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: automatic merge for master
    conditions:
      - base=master
      - -draft
      - or:
        - "#approved-reviews-by>=1"
        - and:
          - author=fallobst22
          - "body~=#ignore-review"
    actions:
      queue:
  - name: automatic approve for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=Bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      review:
  - name: assign pr
    conditions:
      - -draft
      - or:
        - -author~=^dependabot(|-preview)\[bot\]$
        - -title~=Bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      assign:
        add_users:
          - fallobst22
      request_reviews:
        users:
          - fallobst22
